In [24]:
import torch

In [25]:
import torch.nn as nn


In [26]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()


    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [27]:
featrues = torch.rand(10,5)
model = Model(featrues.shape[1])

model(featrues)

tensor([[0.5328],
        [0.5596],
        [0.5533],
        [0.5117],
        [0.5534],
        [0.5226],
        [0.5140],
        [0.5123],
        [0.5334],
        [0.5534]], grad_fn=<SigmoidBackward0>)

In [29]:
model.linear1.bias

Parameter containing:
tensor([ 0.1774, -0.1911, -0.4289], requires_grad=True)

In [30]:
model.linear1.bias

Parameter containing:
tensor([ 0.1774, -0.1911, -0.4289], requires_grad=True)

In [31]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [32]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.sigmoid()
        )


    def forward(self,features):
        out = self.network(featrues)

        return out