In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print({torch.cuda.get_device_name()})
else:
    print("not found")

{'NVIDIA GeForce RTX 4050 Laptop GPU'}


## Creating a Tensor

In [3]:
a = torch.empty(2,3)
print(a)

tensor([[-9.6969e-27,  1.4910e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)  # 0 -> 1 random values

tensor([[0.8417, 0.6083, 0.5598],
        [0.0437, 0.0357, 0.4354]])

In [8]:
torch.rand(2,3)   # different

tensor([[0.2862, 0.8282, 0.6217],
        [0.3448, 0.3771, 0.5715]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)  # same upper and loser random value

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.arange(0,25,4)

tensor([ 0,  4,  8, 12, 16, 20, 24])

In [13]:
torch.linspace(0,15,7)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000, 12.5000, 15.0000])

In [14]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [15]:
torch.full((2,3),7)

tensor([[7, 7, 7],
        [7, 7, 7]])