In [45]:
import torch

In [46]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
x.shape

torch.Size([2, 3])

In [48]:
torch.empty_like(x) # random value come

tensor([[2505320701296,             0,             0],
        [            0,             0,             0]])

In [49]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [50]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x)  not work
