In [1]:
import torch

In [3]:
x = torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [4]:
x.dtype

torch.int64

In [ ]:
torch.tensor([2.0,3.5,9.0],dtype=torch.int32)

tensor([2, 2, 9], dtype=torch.int32)

In [6]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [7]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [3., 4., 5.]], dtype=torch.float64)

In [8]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.6911, 0.3713, 0.1935],
        [0.7557, 0.5887, 0.4513]], dtype=torch.float64)