In [1]:
import torch

In [2]:
x = torch.rand(2,3)
x

tensor([[0.2963, 0.0475, 0.9759],
        [0.5969, 0.6624, 0.1663]])

## Scaler

In [3]:
x + 2

tensor([[2.2963, 2.0475, 2.9759],
        [2.5969, 2.6624, 2.1663]])

In [4]:
x-2

tensor([[-1.7037, -1.9525, -1.0241],
        [-1.4031, -1.3376, -1.8337]])

In [5]:
x/2

tensor([[0.1481, 0.0238, 0.4880],
        [0.2984, 0.3312, 0.0831]])

In [6]:
x*2

tensor([[0.5926, 0.0951, 1.9518],
        [1.1938, 1.3247, 0.3325]])

In [7]:
# int division
(x * 100)/3

tensor([[ 9.8762,  1.5843, 32.5308],
        [19.8959, 22.0786,  5.5425]])

In [8]:
((x * 100)/3)%2

tensor([[1.8762, 1.5843, 0.5308],
        [1.8959, 0.0786, 1.5425]])

In [9]:
x**2

tensor([[0.0878, 0.0023, 0.9524],
        [0.3563, 0.4387, 0.0276]])

## element wise operation

In [10]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2190, 0.8014, 0.0787],
        [0.2515, 0.1200, 0.6452]])
tensor([[0.3388, 0.5564, 0.3342],
        [0.5908, 0.0307, 0.7167]])


In [11]:
a + b # we do all -,*,/,power,mod

tensor([[0.5579, 1.3578, 0.4128],
        [0.8423, 0.1507, 1.3619]])

In [12]:
a ** b

tensor([[0.5978, 0.8841, 0.4276],
        [0.4425, 0.9369, 0.7304]])

In [13]:
a%b

tensor([[0.2190, 0.2450, 0.0787],
        [0.2515, 0.0278, 0.6452]])

In [14]:
c= torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [15]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [17]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [16]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [18]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [19]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [20]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [21]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])