In [1]:
import torch

In [5]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[0, 1, 1],
        [7, 9, 9]])
tensor([[9, 5],
        [0, 2],
        [4, 6]])


In [7]:
torch.matmul(f,g) #matrix multification

tensor([[  4,   8],
        [ 99, 107]])

In [8]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

In [9]:
torch.dot(v1,v2)

tensor(11)

In [12]:
f

tensor([[0, 1, 1],
        [7, 9, 9]])

In [13]:
torch.transpose(f,0,1)
torch.transpose(f,1,0)

tensor([[0, 7],
        [1, 9],
        [1, 9]])

In [ ]:
x = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float64)

torch.det(x)

tensor(-186., dtype=torch.float64)

In [17]:
x

tensor([[6., 2., 6.],
        [1., 6., 4.],
        [4., 6., 1.]], dtype=torch.float64)

In [19]:
torch.inverse(x)

tensor([[ 0.0968, -0.1828,  0.1505],
        [-0.0806,  0.0968,  0.0968],
        [ 0.0968,  0.1505, -0.1828]], dtype=torch.float64)

## Comparision operatiors

In [24]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[8, 9, 8],
        [3, 0, 3]])
tensor([[5, 3, 6],
        [5, 8, 5]])


In [25]:
i>j

tensor([[ True,  True,  True],
        [False, False, False]])

In [26]:
i<=j

tensor([[False, False, False],
        [ True,  True,  True]])

## Special function

In [27]:
torch.log(f)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 2.1972]])

In [28]:
torch.exp(f)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 8.1031e+03]])

In [29]:
torch.sqrt(f)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 3.0000]])

In [30]:
torch.sigmoid(f)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9999]])

In [31]:
x

tensor([[6., 2., 6.],
        [1., 6., 4.],
        [4., 6., 1.]], dtype=torch.float64)

In [32]:
torch.softmax(x,dim=1)

tensor([[0.4955, 0.0091, 0.4955],
        [0.0059, 0.8756, 0.1185],
        [0.1185, 0.8756, 0.0059]], dtype=torch.float64)

In [33]:
torch.relu(f)

tensor([[0, 1, 1],
        [7, 9, 9]])