## Inplace Operation

In [41]:
import torch

In [42]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.1799, 0.2935, 0.4045],
        [0.5814, 0.9978, 0.7286]])
tensor([[0.3184, 0.3290, 0.5390],
        [0.6600, 0.4568, 0.3950]])


In [43]:
m.add_(n)

tensor([[0.4983, 0.6224, 0.9434],
        [1.2414, 1.4546, 1.1235]])

In [44]:
m

tensor([[0.4983, 0.6224, 0.9434],
        [1.2414, 1.4546, 1.1235]])

In [45]:
n

tensor([[0.3184, 0.3290, 0.5390],
        [0.6600, 0.4568, 0.3950]])

In [46]:
m.relu_()

tensor([[0.4983, 0.6224, 0.9434],
        [1.2414, 1.4546, 1.1235]])

In [47]:
m

tensor([[0.4983, 0.6224, 0.9434],
        [1.2414, 1.4546, 1.1235]])

## Copy a tensor

In [48]:
a = torch.rand(2,3)
a

tensor([[0.8734, 0.4248, 0.8137],
        [0.9337, 0.4892, 0.8710]])

In [49]:
b = a

In [50]:
b

tensor([[0.8734, 0.4248, 0.8137],
        [0.9337, 0.4892, 0.8710]])

In [51]:
a[0][0] = 0

In [52]:
a

tensor([[0.0000, 0.4248, 0.8137],
        [0.9337, 0.4892, 0.8710]])

In [53]:
b  # change come in b also
# means changes in both original or copy 

tensor([[0.0000, 0.4248, 0.8137],
        [0.9337, 0.4892, 0.8710]])

In [54]:
print(id(a))
print(id(b))

2387516595056
2387516595056


In [55]:
b = a.clone()

In [56]:
print(id(a))
print(id(b)) # different location so changes not in both if i change any one

2387516595056
2387516503072


## Tensor in gpu

In [57]:
torch.cuda.is_available()

True

In [58]:
device = torch.device('cuda')

In [59]:
# creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.0983, 0.8457, 0.9781],
        [0.6905, 0.5249, 0.0674]], device='cuda:0')

In [60]:
# moving a existing tensor on gpu
b = m.to(device)

In [61]:
b + 5

tensor([[5.4983, 5.6224, 5.9434],
        [6.2414, 6.4546, 6.1235]], device='cuda:0')

##  Reshaping tensors

In [64]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [66]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
b = torch.rand(2,3,4)
b

tensor([[[0.6253, 0.8043, 0.1203, 0.6790],
         [0.9561, 0.8165, 0.8146, 0.5812],
         [0.6546, 0.7020, 0.4635, 0.7614]],

        [[0.8797, 0.4185, 0.4101, 0.0071],
         [0.6714, 0.4076, 0.5900, 0.3943],
         [0.6255, 0.7530, 0.8821, 0.0676]]])

In [69]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [71]:
c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [73]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## numpy and pytorch

In [74]:
import numpy as np

In [75]:
a = torch.tensor([1,2,3])
b = a.numpy()

In [76]:
b

array([1, 2, 3])

In [77]:
type(b)

numpy.ndarray

In [80]:
z = torch.from_numpy(b)

In [82]:
type(z)

torch.Tensor